<?php
/* @var $block MX\MegaMenu\Block\Adminhtml\Menu\Edit\Form */
?>

<div class="mega-menu-form" data-mage-init='{"MXMegaMenuForm":{}}'>
    <?php echo $block->getFormHtml();?>
    <div class="content-footer">
        <p class="form-buttons">
            <button title="<?php echo __('Save'); ?>" type="button" class="action-default scalable action-primary add-widget">
                <span><?php echo __('Save'); ?></span>
            </button>
        </p>
    </div>
</div>
