<?php
    /** @var $block \MX\MegaMenu\Block\Topmenu */
?>

<div class="mx-megamenu topmenu">
    <nav class="navigation" data-action="navigation">
        <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}, "mediaBreakpoint": "(max-width: 960px)"}}'>
            <?php echo $block->getChildHtml('mx.megamenu.structure'); ?>
        </ul>
    </nav>
</div>


