<?php

/** @var $block \MX\MegaMenu\Block\Topmenu */

$structure = $block->getStructure();

?>

<?php if ($structure): ?>
    <?php foreach ($structure as $item): ?>
        <?php if ($item['status']): ?>
            <li class="level0 level-top parent mx-megamenu__item <?php echo $item['custom_class']; ?>">
                <a href="<?php echo $item['link']; ?>" class="nav-anchor mx-megamenu__link">
                    <span><?php echo $item['name']; ?></span>
                </a>
                <?php if ($block->canShowContent($item)): ?>
                    <div class="level0 mx-megamenu__submenu submenu">
                        <?php if ($item['header_status']): ?>
                            <div class="mx-megamenu__header">
                                <?php echo $item['header_content']; ?>
                            </div>
                        <?php endif; ?>
                        <div class="mx-megamenu__content">
                            <?php if ($item['leftside_status']): ?>
                                <div class="mx-megamenu__sidebar mx-megamenu__sidebar--left">
                                    <?php echo $item['leftside_content']; ?>
                                </div>
                            <?php endif; ?>
                            <?php echo $block->renderChildren($item, true); ?>
                            <?php if ($item['rightside_status']): ?>
                                <div class="mx-megamenu__sidebar mx-megamenu__sidebar--right">
                                    <?php echo $item['rightside_content']; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                        <?php if ($item['footer_status']): ?>
                            <div class="mx-megamenu__footer">
                                <?php echo $item['footer_content']; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>

