<?php

/** @var $block \MX\MegaMenu\Block\Topmenu\Children */

$item = $block->getItem();
$level = $block->getItemLevel($item);
$levelClass = 'level' . $level;
$first = $block->getFirst();

?>
<?php if ($item['status']): ?>
    <?php if (!empty($item['content_categories'])): // Render category items ?>
        <div class="mx-megamenu__item mx-megamenu__category category-item <?php echo $item['custom_class']; ?>">
            <?php $categories = $item['content_categories']; ?>
            <?php if (isset($categories['category'])): ?>
                <?php $category = $categories['category']; ?>
                <?php $categoryLink = 'javascript:;'; ?>
                <?php if (!empty($category['link'])): ?>
                    <?php $categoryLink = $category['link']; ?>
                <?php endif; ?>
                <a href="<?php echo $categoryLink; ?>" class="nav-anchor mx-megamenu__link <?php echo $item['content_category_type']; ?>">
                    <span><?php echo $category['name']; ?></span>
                </a>
                <?php if (count($categories['children'])): ?>
                    <div class="mx-megamenu__submenu">
                        <?php foreach ($categories['children'] as $subcategory): ?>
                            <div class="mx-megamenu__category-item category-item">
                                <a id="u-uid-<?php echo $subcategory['id']; ?>" class="mx-megamenu__link" href="<?php echo $subcategory['link']; ?>">
                                    <span><?php echo $subcategory['name']; ?></span>
                                </a>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    <?php elseif (!empty($item['link']) && !$first): // Render custom items and does not duplicate parent item as the main item is pulled through ?>
        <div class="<?php echo $levelClass; ?> mx-megamenu__item mx-megamenu__category category-item <?php echo $item['custom_class']; ?>">
            <a href="<?php echo $item['link']?>" class="nav-anchor mx-megamenu__link">
                <span><?php echo $item['name']; ?></span>
            </a>
            <?php if (isset($item['wrapper'])): ?>
                <div class="mx-megamenu__submenu wrapper">
            <?php endif; ?>
        </div>
    <?php else: ?>
        <?php if ($item['content_status']): // Content is displayed if no children stuff is found ?>
            <div class="mx-megamenu__main-content">
                <?php echo $item['content_content']; ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <?php if (isset($item['children'])): //There is one more level specified ?>
        <?php foreach ($item['children'] as $childId => $child): ?>
            <?php echo $block->getParentBlock()->renderChildren($child); ?>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php if (isset($item['wrapper'])): ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
